services:
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://urls_user:urls_pass@db:5432/url_shortener_db
    volumes:
      - ./src:/app/src:ro
    ports:
      - "8000:8000"
    command: .venv/bin/fastapi run src/main.py --host 0.0.0.0 --port 8000 --reload